# Simulation parameters
AT_TARGET_ACCEPTANCE_THRESHOLD = 0.1
SHOW_ANIMATION = True
TIME_STEP = 0.01
# Robot specifications
MAX_LINEAR_SPEED = 15
MAX_ANGULAR_SPEED = 7

PLOT_WINDOW_SIZE_X = 20
PLOT_WINDOW_SIZE_Y = 20